name: amber_road
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.1
  flutter_local_notifications: ^19.2.0

  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0

  image_picker: ^1.1.2

  reorderable_grid_view: ^2.2.8
  photo_view: ^0.15.0

  font_awesome_flutter: ^10.8.0
  provider: ^6.1.4
  uuid: ^4.5.1

  intl: ^0.20.2
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
